#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long qw/:config posix_default no_ignore_case bundling auto_help/;
use Plack::Loader;
use Ukigumo::Server::CLI;

GetOptions(\my %opt, qw/
    port=s
    host=s
    config=s
    max-workers=i
/);
$opt{host}          //= 0;
$opt{port}          //= 2828;
$opt{'max-workers'} //= 4;

$ENV{PLACK_ENV} //= 'development';
local $0 = "$0 (Ukigumo::Server)"; # steal from growthforecast.pl

Ukigumo::Server::CLI->set_config($opt{config});
Ukigumo::Server::CLI->setup;
my $app = Ukigumo::Server::CLI->to_app;

my $loader = Plack::Loader->load('Starlet',
    port        => $opt{port},
    host        => $opt{host},
    max_workers => $opt{'max-workers'},
);

printf "ukigumo-server starts listen on %s:%s\n", $opt{host}, $opt{port};

$loader->run($app);

__END__

=head1 NAME

ukigumo-server - ukigumo server launcher

=head1 SYNOPSIS

    % ukigumo-server
        --host=127.0.0.1 # Bind host   (Default: 0)
        --port=80        # Bind port   (Default: 2828)
        --max-workers    # Max workers (Default: 4)

=head1 DESCRIPTION

ukigumo-server is a Ukigumo::Server launcher.
